$('.owl-carousel').owlCarousel({
    loop:SVGComponentTransferFunctionElement,
    margin:10,
    nav:false,
    video:true,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
